// Mocks generated by Mockito 5.4.6 from annotations
// in easier_drop/test/screens/file_transfer_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:easier_drop/model/file_reference.dart' as _i3;
import 'package:easier_drop/providers/files_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:share_plus/share_plus.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeObject_0 extends _i1.SmartFake implements Object {
  _FakeObject_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FilesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesProvider extends _i1.Mock implements _i2.FilesProvider {
  @override
  bool get isEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isEmpty),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasFiles =>
      (super.noSuchMethod(
            Invocation.getter(#hasFiles),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get fileCount =>
      (super.noSuchMethod(
            Invocation.getter(#fileCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get recentlyAtLimit =>
      (super.noSuchMethod(
            Invocation.getter(#recentlyAtLimit),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.FileReference> get files =>
      (super.noSuchMethod(
            Invocation.getter(#files),
            returnValue: <_i3.FileReference>[],
            returnValueForMissingStub: <_i3.FileReference>[],
          )
          as List<_i3.FileReference>);

  @override
  List<_i4.XFile> get validXFiles =>
      (super.noSuchMethod(
            Invocation.getter(#validXFiles),
            returnValue: <_i4.XFile>[],
            returnValueForMissingStub: <_i4.XFile>[],
          )
          as List<_i4.XFile>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> addFile(_i3.FileReference? file) =>
      (super.noSuchMethod(
            Invocation.method(#addFile, [file]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addFiles(Iterable<_i3.FileReference>? files) =>
      (super.noSuchMethod(
            Invocation.method(#addFiles, [files]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeFile(_i3.FileReference? file) =>
      (super.noSuchMethod(
            Invocation.method(#removeFile, [file]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void removeByPath(String? pathname) => super.noSuchMethod(
    Invocation.method(#removeByPath, [pathname]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<Object> shared({_i6.Offset? position}) =>
      (super.noSuchMethod(
            Invocation.method(#shared, [], {#position: position}),
            returnValue: _i5.Future<Object>.value(
              _FakeObject_0(
                this,
                Invocation.method(#shared, [], {#position: position}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<Object>.value(
              _FakeObject_0(
                this,
                Invocation.method(#shared, [], {#position: position}),
              ),
            ),
          )
          as _i5.Future<Object>);

  @override
  void rescanNow() => super.noSuchMethod(
    Invocation.method(#rescanNow, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addFileForTest(_i3.FileReference? ref) => super.noSuchMethod(
    Invocation.method(#addFileForTest, [ref]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
