name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests and coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate Localizations
        run: flutter gen-l10n
        
      - name: Run tests with coverage
        run: flutter test --coverage
        
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
